#services:
#  postgres:
#    container_name: mysql-sql
#    image: mysql
#    environment:
#      MYSQL_USER: username
#      MYSQL_PASSWORD: password
#      MYSQLDATA: /data/postgres
#    volumes:
#      - mysql:/data/postgres
#    ports:
#      - "5432:5432"
#    networks:
#      - mysql
#    restart: unless-stopped
#
#  mysql:
#    container_name: pgadmin
#    image: dpage/pgadmin4
#    environment:
#      MYSQL_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
#      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
#      PGADMIN_CONFIG_SERVER_MODE: 'False'
#    volumes:
#      - pgadmin:/var/lib/pgadmin
#    ports:
#      - "5050:80"
#    networks:
#      - mysql
#    restart: unless-stopped
#
#networks:
#  mysql:
#    driver: bridge
#
#volumes:
#  mysql:
#  pgadmin: