### Register User
POST http://localhost:8080/api/v1/auth/register
Content-Type: application/json

{
  "firstname": "moin",
  "lastname": "malik",
  "email":  "themoinmalik@gmail.com",
  "password": "hello0702",
  "role":  "ADMIN"
}

> {% client.global.set("auth-token", response.body.access_token);  %}


###Create a new book
POST http://localhost:8080/api/v1/books/create
Authorization: Bearer {{auth-token}}
Content-Type: application/json

{
  "author": "moin malik",
  "name": "java with springboot"
}

### Query Books
@Id = variable value   # eg: 1
GET http://localhost:8282/api/v1/books/{{Id}}}
Authorization: Bearer {{auth-token}}

### Update one book
POST http://localhost:8282/api/v1/books/create
Authorization: Bearer {{auth-token}}
Content-Type: application/json

{
  "id": 1,
  "author": "moin moin",
  "isbn": "java with springboot"
}


### Query the Books one more time
GET http://localhost:8282/api/v1/books/findAll
Authorization: Bearer {{auth-token}}
